src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('shoes.urls')),
    path('', include('phys.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/phys/urls.py
from django.urls import path
from . import views

app_name = 'phys'

urlpatterns = [
    path('phys/list/', views.phys_data_list, name='phys_data_list'),
    path('phys/list/<kidsProfileId>', views.phys_data_list, name='phys_data_list'),
    path('phys/data_add/', views.phys_data_add, name='phys_data_add'),
    path('phys/data_edit/<dataPostId>', views.phys_data_edit, name='phys_data_edit'),
    path('phys/data_delete/', views.phys_data_delete, name='phys_data_delete'),
    path('phys/graph/', views.graph_page_display, name='graph_page_display'),
    path('phys/graph/<kidsProfileId>', views.graph_page_display, name='graph_page_display'),
    path('data/graph_imaga/', views.graph_image_display, name='graph_image_display'),
    path('data/graph_imaga/<kidsProfileId>', views.graph_image_display, name='graph_image_display'),
]

src/shoes/urls.py
from django.urls import path
from . import views

app_name = 'shoes'

urlpatterns = [
    path('shoes/list/', views.shoes_data_list, name='shoes_data_list'),
    path('shoes/list/<kidsProfileId>', views.shoes_data_list, name='shoes_data_list'),
    path('shoes/data_add/', views.shoes_data_add, name='shoes_data_add'),
    path('shoes/data_edit/<shoesDataId>', views.shoes_data_edit, name='shoes_data_edit'),
    path('shoes/data_delete/<shoesDataId>', views.shoes_data_delete, name='shoes_data_delete'),
]

src/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.mypage, name='mypage'),
    path('signup/', views.signup, name='signup'),
    path('mypage/', views.mypage, name='mypage'),
    path('login/', views.login_mypage.as_view(), name='login'),
    path('logout/', views.logout.as_view(), name='logout'),
    path('kids_profile_add/', views.kids_profile_add, name='kids_profile_add'),
    path('kids_profile_edit/<kidsProfileId>', views.kids_profile_edit, name='kids_profile_edit'),
    path('kids_profile_delete/<kidsProfileId>', views.kids_profile_delete, name='kids_profile_delete'),
]

src/templates/base.html
{% load static %}

<html>
    <head>
        <title>kids Growth</title>

        <link rel="stylesheet" href="{% static 'css/kidsGrowth.css' %}">
        <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
        <script src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>
        {% block extra_js %}{% endblock %}
        {% load bootstrap4 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
              <span class="sr-only">メニュー</span>  
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="">Kids Growth</a>
            <div class="collapse navbar-collapse" id="navbarNav4">
                <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'phys:phys_data_list' %}">身長体重データ</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'phys:graph_page_display' %}">成長曲線</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'shoes:shoes_data_list' %}">シューズ一覧</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'users:mypage' %}">マイページ</a>
                  </li>
                  {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">ログアウト</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">ログイン</a>
                    </li>
                  {% endif %}
                </ul>
            </div>
        </nav>

        <div class="content container">
		  {% block content %}
          {% endblock %}
        </div>
    </body>
</html>