src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('shoes.urls')),
    path('', include('phys.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/phys/urls.py
from django.urls import path
from . import views

app_name = 'phys'

urlpatterns = [
    path('phys/list/', views.phys_data_list, name='phys_data_list'),
    path('phys/list/<kidsProfileId>', views.phys_data_list, name='phys_data_list'),
    path('phys/data_add/', views.phys_data_add, name='phys_data_add'),
    path('phys/data_edit/<dataPostId>', views.phys_data_edit, name='phys_data_edit'),
    path('phys/data_delete/', views.phys_data_delete, name='phys_data_delete'),
    path('phys/graph/', views.graph_page_display, name='graph_page_display'),
    path('phys/graph/<kidsProfileId>', views.graph_page_display, name='graph_page_display'),
    path('data/graph_imaga/', views.graph_image_display, name='graph_image_display'),
    path('data/graph_imaga/<kidsProfileId>', views.graph_image_display, name='graph_image_display'),
]

src/shoes/urls.py
from django.urls import path
from . import views

app_name = 'shoes'

urlpatterns = [
    path('shoes/list/', views.shoes_data_list, name='shoes_data_list'),
    path('shoes/list/<kidsProfileId>', views.shoes_data_list, name='shoes_data_list'),
    path('shoes/data_add/', views.shoes_data_add, name='shoes_data_add'),
    path('shoes/data_edit/<shoesDataId>', views.shoes_data_edit, name='shoes_data_edit'),
    path('shoes/data_delete/<shoesDataId>', views.shoes_data_delete, name='shoes_data_delete'),
]

src/shoes/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from users.models import KidsProfile

#靴データ
class ShoesData(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
    kidsProfile = models.ForeignKey(KidsProfile, on_delete=models.CASCADE,null=True)
    buy_date = models.DateField(default=timezone.now)
    shoes_size = models.DecimalField(
                max_digits=3,
                decimal_places=1,
                choices = ((x/2, str(x/2)) for x in range(16,50,1)),
                blank = False
                )
    shoes_memo = models.TextField(blank=True, null=True)
    shoes_image = models.ImageField(upload_to="image/", blank=True)

    def __str__(self):
        return self.kidsProfile.name + str(self.buy_date)

src/shoes/forms.py
from django import forms
from .models import ShoesData
from users.models import KidsProfile
import bootstrap_datepicker_plus as datetimepicker


class ShoesDataForm(forms.ModelForm):
    class Meta:
        model = ShoesData
        fields = ('kidsProfile', 'buy_date', 'shoes_size', 'shoes_memo', 'shoes_image')
        widgets = {
            'buy_date': datetimepicker.DatePickerInput(
                           format='%Y-%m-%d'),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user','')
        super(ShoesDataForm, self).__init__(*args, **kwargs)
        self.fields['kidsProfile'] = forms.ModelChoiceField(queryset=KidsProfile.objects.filter(user=user))

class ShoesDataEditForm(forms.ModelForm):
    class Meta:
        model = ShoesData
        fields = ('buy_date', 'shoes_size', 'shoes_memo', 'shoes_image')
        widgets = {
            'buy_date': datetimepicker.DatePickerInput(
                           format='%Y-%m-%d'),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user','')
        kidsProfileId = kwargs.pop('kidsProfileId','')
        super(ShoesDataEditForm, self).__init__(*args, **kwargs)

src/shoes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import ShoesData
from users.models import KidsProfile
from .forms import ShoesDataForm, ShoesDataEditForm


#靴リスト
@login_required
def shoes_data_list(request, **kwargs):
    user_name = request.user
    try:
        if len(kwargs) > 0:
            kids_profile_id = kwargs["kidsProfileId"]
        else:
            kids_profile_id = KidsProfile.objects.filter(user=user_name).first().id

        kids_profiles = KidsProfile.objects.filter(user=user_name) #子供情報選択用
        kids_profile_name  = KidsProfile.objects.get(id=kids_profile_id).name
        shoes_data_posts = ShoesData.objects.filter(user=user_name, kidsProfile=kids_profile_id).order_by('buy_date')

    except AttributeError:
        shoes_data_posts = None
        kids_profiles = None
        kids_profile_name = "子供情報を登録してください"

    params = {
        'shoes_data_posts' : shoes_data_posts,
        'kidsProfiles' : kids_profiles,
        'kidsName' : kids_profile_name,
    }
    return render(request, 'shoes/shoes_data_list.html', params)

#靴データを新規追加
@login_required
def shoes_data_add(request):
    user_name = request.user
    if request.method == 'POST':
      form = ShoesDataForm(request.POST, user = user_name)
      if form.is_valid():
        data = form.save(commit=False)
        if request.FILES.get('shoes_image') is None:
            pass
        else:
            data.shoes_image = request.FILES.get('shoes_image')
        data.user = user_name
        data.save()
        return redirect('shoes:shoes_data_list')
    else:
      form = ShoesDataForm(user = user_name)
    return render(request, 'shoes/shoes_data_add.html', {'form': form})

#靴データを編集
@login_required
def shoes_data_edit(request, shoesDataId):
    shoes_data = ShoesData.objects.get(pk=shoesDataId)
    if request.method == 'POST':
      form = ShoesDataEditForm(request.POST)
      if form.is_valid():
        data = form.save(commit=False)
        data.user = request.user
        data.kidsProfile = shoes_data.kidsProfile
        data.shoes_image = request.FILES.get('shoes_image')
        data.save()
        shoes_data.delete()
        return redirect('shoes:shoes_data_list')
    else:
      form = ShoesDataEditForm(
        {
          'buy_date' : shoes_data.buy_date ,
          'shoes_size' : shoes_data.shoes_size ,
          'shoes_memo' : shoes_data.shoes_memo ,
          'shoes_image' : shoes_data.shoes_image
        },
        user = request.user
      )
    return render(request, 'shoes/shoes_data_edit.html', {'form': form})

#靴データを削除
@login_required
def shoes_data_delete(request, shoesDataId):
    ShoesData.objects.get(id=shoesDataId).delete()
    return redirect('shoes:shoes_data_list')

src/templates/shoes/shoes_data_add.html
{% extends 'base.html' %}

{% block content %}

<!--日付入力フォーマット用-->
{{ form.media }}

<div class="col-md-12 col-lg-5">
    <h2>New data</h2>
    <form method="POST" class="post-form"  enctype="multipart/form-data">{% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

src/templates/shoes/shoes_data_edit.html
{% extends 'base.html' %}

{% block content %}

<!--日付入力フォーマット用-->
{{ form.media }}

<div class="col-md-12 col-lg-5">
    <h2>Data Edit</h2>
    <form method="POST" class="post-form"  enctype="multipart/form-data">{% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

src/templates/shoes/shoes_data_list.html
{% extends 'base.html' %}

{% block extra_js %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).data("pk"));
     $('#del_url').attr('href', $(this).data("url"));

     $(this).attr('href', href);
  });
});
</script>
{% endblock extra_js %}

{% block content %}
<div class="row">
    <div class="col-md-12 col-lg-2">
        <div class="list-group">
          {% for kidsProfile in kidsProfiles %}
            <a href="/shoes/list/{{kidsProfile.id}}" class="list-group-item list-group-item-action">{{kidsProfile.name}}</a>
          {% endfor %}
        </div>
    </div>
    <div class="col-md-12 col-lg-10 overflow-auto">

        <div class="card">
            <div class="card-header">
                {{ kidsName }}
            </div>

            <div class="card-body">
                <div class="container-fluid">
                    {% for shoes_data_post in shoes_data_posts %}
                    <div class="row">
                        {% if shoes_data_post.shoes_image %}
                            <a href="{{ shoes_data_post.shoes_image.url }}"
                               style="background-image: url({{ shoes_data_post.shoes_image.url }})"
                               class="col-4 col-lg-2 border shoes_img" data-lightbox="demo"></a>
                        {% else %}
                            <a href="/static/images/noimage.png"
                               style="background-image: url(/static/images/noimage.png)"
                               class="col-4 col-lg-2 border shoes_img" data-lightbox="demo"></a>
                        {% endif %}
                        <div class="col-8 col-lg-10 pl-lg-5">
                            <div class="row">
                                <div class="col-md-12 col-lg-2 mb-2 rounded bg-secondary">名前</div>
                                <div class="col-md-12 col-lg-3 mb-2">{{ shoes_data_post.kidsProfile }}</div>
                                <div class="col-md-0  col-lg-7 "></div>
                                <div class="col-md-12 col-lg-2 mb-2 rounded bg-secondary">購入日</div>
                                <div class="col-md-12 col-lg-3 mb-2">{{ shoes_data_post.buy_date }}</div>
                                <div class="col-md-0  col-lg-1 "></div>
                                <div class="col-md-12 col-lg-2 mb-2 rounded bg-secondary">サイズ</div>
                                <div class="col-md-12 col-lg-3 mb-2">{{ shoes_data_post.shoes_size }}cm</div>
                                <div class="col-md-0  col-lg-1 "></div>
                                <div class="w-100"></div>
                                <div class="col-lg-2 rounded bg-secondary">メモ</div>
                                <div class="col-lg-10">{{ shoes_data_post.shoes_memo }}</div>
                                <div class="col-12 text-right mt-2">
                                    <a href="{% url 'shoes:shoes_data_edit' shoes_data_post.id %}" role="button" class="btn btn-success btn-sm">編集</a>
                                    <button type="button" class="btn btn-danger btn-sm del_confirm" data-toggle="modal" data-target="#delete_modal"
                                        data-pk="{{ shoes_data_post.pk }}" data-url="{% url 'shoes:shoes_data_delete' shoes_data_post.id %}">削除</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
        <a href="{% url 'shoes:shoes_data_add' %}" role="button" class="btn btn-primary mr-auto">追加</a>


        <div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">
                        削除しても良いですか？
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                        <a href="#" id="del_url" class="btn btn-danger">削除</a>
                    </div>
                 </div>
             </div>
        </div>
    </div>
{% endblock %}